kind: pipeline
name: default

steps:
  - name: linter
    image: golang:latest
    environment:
      GOPROXY: https://mirrors.aliyun.com/goproxy/
    commands:
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - golangci-lint run

  - name: build
    image: golang:latest
    environment:
      GOPROXY: https://mirrors.aliyun.com/goproxy/
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go build -o demo-app

  - name: docker
    image: plugins/docker
    settings:
      repo: gaotong/drone-k8s-demo
      use_cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

    tags:
    - latest
    when:
      event: push
      branch: master


